services:
  stats-server:
    build:
      context: ./stat-svc/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      statdb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://statdb:5432/statdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - STATS_SERVER_URL=http://stats-server:9090
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9090/actuator/health | grep UP || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5

  ewm-service:
    build:
      context: ./ewm-main-svc
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewmdb:5432/ewmdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: postgres
      STATS_SERVER_URL: http://stats-server:9090
    depends_on:
      ewmdb:
        condition: service_healthy
      stats-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health | grep UP || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5

  statdb:
    image: postgres:16.1
    container_name: statdb
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=statdb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d statdb" ]
      interval: 10s
      timeout: 10s
      retries: 5

  ewmdb:
    image: postgres:16.1
    container_name: ewmdb
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d ewmdb" ]
      interval: 10s
      timeout: 10s
      retries: 5
      