--liquibase formatted sql

--changeset pavel:001-initial-schema
CREATE TABLE endpoint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(255) NOT NULL,
    ip VARCHAR(15) NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
